### ISSUE TITLE
Cartographic Text labels are very small in ArcGIS Pro

### ISSUE THREAD

**Issue by walkermatt** [OrdnanceSurvey/OSMM-Topography-Layer-stylesheets#11]
I've been testing data loaded with the v9 values populated by [Loader](https://github.com/AstunTechnology/Loader) in ESRI ArcGIS Pro and I've found that the Cartographic Text labels are very small. I only have ArcGIS Pro to test with so I'm wondering if it's the same in ArcMap or whether the labels just need updating in the v9 `.lyr` files?

I'm using the `.lyr` files from [/Schema version 9/Stylesheets/ESRI stylesheets (LYR)/](https://github.com/OrdnanceSurvey/OSMM-Topography-Layer-stylesheets/tree/master/Schema%20version%209/Stylesheets/ESRI%20stylesheets%20(LYR)).

By default the labels are very small:

![arcgis pro - osmm_topo - small labels](https://user-images.githubusercontent.com/600349/29866705-229fc004-8d71-11e7-8e7a-c5b73c067c55.png)

Updating the expression of each class to multiply the `[height]` value by `3.5` appears to provide reasonable labels:

![arcgis pro - osmm_topo - updated labels](https://user-images.githubusercontent.com/600349/29866749-44ad91c6-8d71-11e7-8770-eb413d90f04e.png)

**Comment by charleyglynn** [comment]
Thanks for the feedback Matt.
I will look into this one in more detail. What we're dealing with is trying to find the right balance between label size (and therefore legibility) and the avoidance of clashing/overlapping labels.
It's good to see that you've found a reasonable result - I will look at other options to see if there is an optimal size.
Cheers
Charley
