### ISSUE TITLE
GeoServer can't render some SVG graphics

### ISSUE THREAD

**Issue by walkermatt** [OrdnanceSurvey/OSMM-Topography-Layer-stylesheets#17]
GeoServer 2.13.2 outputs the following error for a number of symbols due the the `rect` SVG element having a `height` attribute with a negative value.

```
2018-09-17 14:29:52,259 DEBUG [geotools.rendering] - Error occurred evaluating external graphic
org.apache.batik.bridge.BridgeException: file:/path/to/geoserver/data_dir/styles/osmmsymbols/positionedConiferousTreeSymbol-backdrop.svg:-1
The attribute "height" of the element <rect> cannot be negative
```

I've found the following affected files:

* `osmmsymbols/culvertSymbol-backdrop.svg`
* `osmmsymbols/positionedConiferousTreeSymbol-backdrop.svg`
* `osmmsymbols/positionedConiferousTreeSymbol-light.svg`
* `osmmsymbols/positionedConiferousTreeSymbol-outdoor.svg`

I've updated my local copies to use a value of `-1` and the symbols appear to display fine but thought I'd check :smile_cat:

**Comment by aaron1uk** [comment]
is there any fix for this?

**Comment by charleyglynn** [comment]
Looking into this now - hopefully have a fix soon and will upload new SVGs.
Cheers
Charley

**Comment by charleyglynn** [comment]
Please let me know if you still find issues with this.
Charley
