### ISSUE TITLE
Incorrect SLD Rule Name for Agricultural Land

### ISSUE THREAD

**Issue by RobQuincey** [OrdnanceSurvey/OSMM-Topography-Layer-stylesheets#18]
https://github.com/OrdnanceSurvey/OSMM-Topography-Layer-stylesheets/blob/4e4c2229eeab2197c995523e976b2753629b6fbd/Schema%20version%209/Stylesheets/Geoserver%20stylesheets%20(SLD)/topographicarea-backdrop.sld#L627

The comment at the line linked to above appears to be for Agricultural land, but the description says 'Mixed Woodland'. The style code appears to align with the 'Agricultural Land Fill' style description. I'm guessing its just the SLD Rule Name that is wrong, but thought it should be flagged as it confused me initially! More instances of this error may exist.

**Comment by charleyglynn** [comment]
Thanks for spotting this Rob. Fixed now.
Charley.
