### ISSUE TITLE
Schema v9 - OSMM. Labels missing in Geoserver

### ISSUE THREAD

**Issue by MiquelRS** [OrdnanceSurvey/OSMM-Topography-Layer-stylesheets#21]
Hi, have translated original GZ to shapefiles, matching Schema v9, and we're serving them from Geoserver as WMS. While we know we have the correct data/structure and performance is good, some labels fail to render when loaded from Geoserver.

It happens when the label is partly outside the frame (which is expected behavior) but also for some street names that fall 100% inside the map frame. The point with the labeling attributes exists, but label won't generate. See image below where the red circle shows a point that should have an associated label, but it doesn't

![image](https://user-images.githubusercontent.com/50410624/57379420-ce371a80-719e-11e9-903d-d6d20379fd22.png)

I know this is related to how Geoserver processes images, because when tiling the WMS in different sizes, results change. Generally, using bigger tiles allows creating more labels but this is not ideal because we don't want to be generating big tiles all the time. Also, some labels as the one in the image will never generate even using large tiles.

A workaround would be creating smaller labels by modifying Schema v9 or Stylesheets. I'm confident that this would solve the issue, but again not ideal because we don't want to modify Schema v9 styling. Also would do if there was a conflict resolution parameter for Geoserver, but I'm afraid there's not.

Somebody found the same issue and experimenting with workarounds?

**Comment by dragons8mycat** [comment]
Hi,
I recently had a similar issue and noticed that the labels are set to "metres" rather than pixels (issue 1) and then also they didn't alter by scale. I had a play with the Geoserver "wms_scale_denominator" function which seems to fix the problem for me.
Let me know if you need some help with it (I have an SLD which you can try to see if it solves your problem)

**Comment by dragons8mycat** [comment]
Try this:
[OSMM_TEXT_NDU.zip](https://github.com/OrdnanceSurvey/OSMM-Topography-Layer-stylesheets/files/3161241/OSMM_TEXT_NDU.zip)

**Comment by MiquelRS** [comment]
Hi, thanks @dragon8mycat for your answer. I'll give it a try and let you know. I did more research and found out that by default the SLD TextSymbolizer sets conflictResolution param to "true", thus preventing label overlapping by removing some of them. Have added the parameter <VendorOption name="conflictResolution">false</VendorOption> and by doing this, those labels that failed to draw because of label conflict now are rendered. This should be fine in the case of OSMM because labels have been intentionally designed to not to overlap.
However, the problem doesn't end here because when tiling the WMS, only those labels that fall 100% inside a tile are rendered. Otherwise they aren't. As I mentioned in the first post, this can be partially solved by serving bigger tiles but not ideal solution. There's another SLD parameter <VendorOption name="partials">false</VendorOption> that draws all labels even if they fall partly outside the tile. This makes all labels to draw but they get eventually cut at the tile edge, so what you see is a lot of cut labels in the tile edges.
I'll give it a try to your solution and see if I can make any progress.
Thanks so much.

**Comment by TimJMartin** [comment]
Looks like this is now resolved so closing the issue, but if there is anything else let us know
