### ISSUE TITLE
Scale dependent rendering - scale ranges 

### ISSUE THREAD

**Issue by spwgit** [OrdnanceSurvey/OSMM-Topography-Layer-stylesheets#22]
There appears to be a problem with the minimum and maximum scale being 'switched' which did not occur when loading the topographic layers into QGis on previous occasions. I have included snippets below to illustrate...

<!DOCTYPE qgis PUBLIC 'http://mrcc.com/qgis.dtd' 'SYSTEM'>
<qgis version="3.4.8-Madeira" minScale="4000" simplifyDrawingTol ="1" simplifyMaxScale="1" maxScale="0" readOnly="0" styleCategories="AllStyleCategories" 

<!DOCTYPE qgis PUBLIC 'http://mrcc.com/qgis.dtd' 'SYSTEM'>
<qgis version="2.18.7"  minimumScale="-4.65661e-10" maximumScale="4000" simplifyDrawingHints="0" minLabelScale="0" maxLabelScale="1e+08" simplifyAlgorithm="0"

<!DOCTYPE qgis PUBLIC 'http://mrcc.com/qgis.dtd' 'SYSTEM'>
<qgis version="2.12.0-Lyon" minimumScale="-4.65661e-10" maximumScale="4000" simplifyDrawingHints="0" minLabelScale= "0" maxLabelScale="1e+08" simplifyDrawingTol="1"

**Comment by TimJMartin** [comment]
We will try and investigate this. These styles were originally written for QGIS 2.x but we do use them in QGIS 3.4 LTR so I will get @egil1978 to investigate

**Comment by egil1978** [comment]
Hi, I have tried replicating this using the stylesheets for schema 9 data but with no luck. I am getting the same scale rendering values for both v2.18 and v3.4. Are you able to confirm the stylesheets you are using are for 9? Many thanks.

**Comment by egil1978** [comment]
Hey @spwgit just wanted to check if this is still an issue or whether it can now be closed? Thanks
