### ISSUE TITLE
Loading of OSMM-Topography-Layer -Stylesheets in QGIS 3.10

### ISSUE THREAD

**Issue by Lozzerdude** [OrdnanceSurvey/OSMM-Topography-Layer-stylesheets#23]
I've struggled for a few days to get the topographicline and topographicarea layers to style according to the QGIS qml stylesheets provided by OS in GITHub.
Much of the posted online help involves using plugins like OS Translator II or PostgreSQL and PostGIS.
After failing with PostgreSQL,  I simply wanted to get it working without setting up a PostgreSQL data source in "localhost".
The qml stylesheets OS provided first need to have various"virtual fields" added to the data tables. This is the tricky bit. The SQL code provided needs to be tinkered with to get it bug free.

I have found a way to make it work and I hope my experience may help other to solve this. Here is how I managed to do it. I suggest you make a copy of your original .gz layer file to work on in QGIS 3.10.

1. For the layers topographicline and topographicarea, the required virtual fields fields can be added separately one after the other using the QGIS Open Field Calculator.
2. First select the topographicline layer
3. Click on Open Attribute Table (icon)
4. Click on Open field calculator (icon)
5. Enter the Output field name as style_description (no quotes)
6. Enter the type as Text (string)
7. Paste the SQL code from attached file [  topographicline SQL (string)-style_description.txt  ]
(the field names have all been amended to include quotes that were not present in the SQL code supplied by OS)
8. This should be error free and should run.
9. On completion open the Data Attribute table and check that the new field has been added as a "virtual field" at the end.
10. Repeat this process for the field style_code (Whole number (integer) size 4). The code for this is in the attached file for style_code. [  topographicline SQL (string)-style_code.txt  ].
11. Once the fields are both in place in the table SAVE THE PROJECT
12. Then Load the OS qml stylesheet for topographicline
13. Repeat this process adding the two same virtual fields to the layer topographicarea.
This requires the SQL code in files topographicarea SQL (string)-style_description.txt and topographicarea SQL (string)-style_code.txt . 
The descriptions and codes are all different for the topographicarea layer.
14. Make sure the layer topographicline is ABOVE the layer topographicarea or it will not be visible
15. Make sure you set the layer visibility to 1 in 6000 by right clicking on the layer. 
16. If you get this to work I suggest you save your Styles under a new name.
17. SAVE THE PROJECT

I have managed to add the other virtual fields in other layers. There are numerous other virtual fields in the cartographictext layer and it was a bit more tedious. I have't yet managed to get the text layer to load the qml stylesheet.

If it works for you please let me know. 

[topographicarea SQL (string)-style_code.txt](https://github.com/OrdnanceSurvey/OSMM-Topography-Layer-stylesheets/files/4232067/topographicarea.SQL.string.-style_code.txt)
[topographicarea SQL (string)-style_description.txt](https://github.com/OrdnanceSurvey/OSMM-Topography-Layer-stylesheets/files/4232068/topographicarea.SQL.string.-style_description.txt)
[topographicline SQL (string)-style_code.txt](https://github.com/OrdnanceSurvey/OSMM-Topography-Layer-stylesheets/files/4232069/topographicline.SQL.string.-style_code.txt)
[topographicline SQL (string)-style_description.txt](https://github.com/OrdnanceSurvey/OSMM-Topography-Layer-stylesheets/files/4232070/topographicline.SQL.string.-style_description.txt)

**Comment by ayounggun** [comment]
Thanks!

**Comment by egil1978** [comment]
This is great @Lozzerdude thank you for taking the time to provide a workaround for people that are uncomfortable with running the SQL's. Are you ok I add these instructions to the repo and if you have them id love to add the .txt files for those too. If not ill look at adding those myself. Thanks again!

**Comment by Lozzerdude** [comment]
Please feel free to use the files anyhow you want.
I'll post the appropriate txt files for other layers as well.
I hope Ordnance Survey will try to keep their qml stylesheet files updated so they work with later versions of QGIS.

**Comment by egil1978** [comment]
Hey @Lozzerdude I am going to start adding the instructions and.txt files you have provided for the OSMM Topo stylesheet workaround and I was wondering if you'd mind sharing the .txt files you have for the other layers too? If you dont have them ill have a go at putting them together myself.

**Comment by Lozzerdude** [comment]
Paul,
Please go ahead and get them working as best you can.
I've not be able to devote any time to this for quite a few days.
If I can get them finished I'll post them alongside the others.
Laurie

On 29 Sep 2020, at 15:22, Paul Naylor <notifications@github.com> wrote:

﻿
Hey @Lozzerdude I am going to start adding the instructions and.txt files you have provided for the OSMM Topo stylesheet workaround and I was wondering if you'd mind sharing the .txt files you have for the other layers too? If you dont have them ill have a go at putting them together myself.

**Comment by egil1978** [comment]
Hey @Lozzerdude , I have now generated the .txt files required for cartographictext, cartographicsymbol, topographicpoint and boundaryline and added these and some working instructions to the repo. Thanks for all you help.
