### ISSUE TITLE
Very Slow ArcMap redraw speed - issue and "fix"

### ISSUE THREAD

**Issue by Eserim** [OrdnanceSurvey/OSMM-Topography-Layer-stylesheets#24]
We were puzzled why redraw in ArcGIS 10.x was so slow using the v9 layers.  The slowness being tracked to MMareas.

At 1:2,000 redraw time was often over 10 seconds, with our old v7 layer files Esri(UK) issued with the Productivity Suite, redraw was 1-3 seconds.

Long story short - it was the fact that the advanced layer options had been switched on in order to control the draw order - as far as I can tell this is so "Slopes" and "Cliffs" that have a diagonal line fill with transparent background, draw on top of whatever other feature they are on top of.

Switching this option off sped up redraw back to acceptable levels and to get Cliff and Slope fills on top I simply added the Area layer again with only these two styles listed (a SQL could be used, but this too slows the redraw,  even if the field is indexed)

**Comment by charleyglynn** [comment]
Thanks for the feedback and solution @Eserim 
We will add a note in the repo :)
