### ISSUE TITLE
OS Mastermap styling not visible

### ISSUE THREAD

**Issue by llmGIS** [OrdnanceSurvey/OSMM-Topography-Layer-stylesheets#26]
I have loaded the boundary line, cartographic symbol, etc .gz files directly into QGIS and I then saved as .shp so I could add a 'style_code' attribute column which I noticed was needed for styling. I have followed the "Styling OS Mastermap Topography Layer Getting Started Guide" for how to use and style GIS GML files. When I Load Style and save all lines/features then disappear from my map. I am presuming I have done something wrong but I can't figure out what, any help would be really appreciated! Thanks in advance. 

Properties set up:

![image](https://user-images.githubusercontent.com/77616598/104906472-a6d8af00-597b-11eb-9c1b-7283d762bf21.png)

Attributes table set up:

![image](https://user-images.githubusercontent.com/77616598/104906548-c243ba00-597b-11eb-9c74-77ec1c7c6ec0.png)

**Comment by egil1978** [comment]
Hi, could we check that you are viewing the data at the correct scale within QGIS for it to be visible? Try zooming in to about 1:2000

**Comment by egil1978** [comment]
Hi, I have just noticed that you have saved the .gml to .shp which is not neccessary. In fact by doing this you will change the attribute headers which will result in the stylesheets not working. This could be your problem?

**Comment by llmGIS** [comment]
Thanks @egil1978 I will give that a try.
