### ISSUE TITLE
FME Suggestion

### ISSUE THREAD

**Issue by citizenfish** [OrdnanceSurvey/OSMM-Topography-Layer-stylesheets#27]
Given that your attribute manipulation requires lowercase attribute names can I suggest you add a BulkAttributeRenamer to the flow as shown below. GML data downloaded from OS has mixed case attribute names

<img width="748" alt="Screenshot 2021-04-08 at 15 51 55" src="https://user-images.githubusercontent.com/10531204/114048473-820d1d00-9882-11eb-9574-60ce19e3fb6c.png">

**Comment by egil1978** [comment]
Hi,
Thanks for this. We will look at getting our FME workbenches updated to include this change.

**Comment by egil1978** [comment]
Hi,
The FME workbenches for applying the new styling attribution have now had the BulkAttributeRenamer transformer added.
Many thanks for raising this issue which I have now closed.
