### ISSUE TITLE
Esri layer file style issues

### ISSUE THREAD

**Issue by gis-geezer** [OrdnanceSurvey/OSMM-Topography-Layer-stylesheets#29]
There are a number of significant issues with the Esri layer files provided:

1) Symbol rotations for Cartographic Symbol are incorrectly defined as "Geographic" when the OS Mastermap spec defines these as counter-clockwise from East (i.e. arithmetic). The expression used for symbol rotation is also incorrect and should instead be something like (orientation * 0.1) + 90. 

2) Symbols and labels associated with style codes in the unique value rendering for Topographic Point are incorrect when compared to the style guide (Related to #28). For example:

- style code 2 should be "Culvert" but is defined as "Emergency Telephone" 
- style code 3 should be "Positioned Nonconiferous Tree" but is defined as "Site Of Heritage"
etc

See below for comparison:

ArcGIS:
![image](https://user-images.githubusercontent.com/74679914/141105312-153322c0-4304-4c4a-a036-6a2d99f7a0f6.png)

Style Guide:
![image](https://user-images.githubusercontent.com/74679914/141105487-1726e914-d505-4cf7-84e3-cd6b4193ff33.png)

**Comment by egil1978** [comment]
Hi @gis-geezer,
Thank you for the feedback. Ill investigate these observations and get back to you shortly.
Paul.

**Comment by egil1978** [comment]
Hi @gis-geezer I have amended the layer files so the rotation expression and type matches the documentation as per your observation and solution. The documentation is in the process of being updated. Thanks for the heads up. Ill close the issue as soon as the documentation is amended. Paul.
