### ISSUE TITLE
fillsymbols error

### ISSUE THREAD

**Issue by waiotahi** [OrdnanceSurvey/OSMM-Topography-Layer-stylesheets#31]
I'm wanting to download some of the symbol fills but they don't appear to render
https://github.com/OrdnanceSurvey/OSMM-Topography-Layer-stylesheets

Also getting error in rendering on single symbols when importing into QGIS (GDV)

**Comment by egil1978** [comment]
Hi, thanks for the question. Have you installed the font and placed the topo symbols in the relevant file on your local drive for QGIS to read them?

**Comment by waiotahi** [comment]
Thanks for the prompt reply

Yes, I assume so

<img width="191" alt="image" src="https://user-images.githubusercontent.com/53323943/161865464-7dceda96-0c2e-4a4a-a789-84fa596f9762.png">

**Comment by egil1978** [comment]
Ok, I am looking into why the GDV symbols are not appearing in QGIS but could you explain the issue you are having with OSMM Topography Layer and the symbols a little more? Are they just not appearing when you load the stylesheets? Everything else ok? Thanks

**Comment by egil1978** [comment]
Hey, I think I have fixed your issue.
Download the toolkit again.
Copy the folder GDV Symbols to C:\Program Files\QGIS xxxx\apps\qgis-ltr\svg, where xxxx represents whatever version of QGIS you are running).
Open QGIS.
Settings > Style Manager.
Import/Export > Import.
Import from File > Navigate to location of XML > Open > Add to favourites > Remove or add any additional tag(s) > Select All > Import
GDV can be found under Tags

Let me know if that works ok and ill close this off.
