### ISSUE TITLE
Mapbox GL style for OSMM Topography Layer (Standard) has incorrect colour for Unclassified Fill

### ISSUE THREAD

**Issue by cam-brown** [OrdnanceSurvey/OSMM-Topography-Layer-stylesheets#34]
The OSMM Topography Layer (Standard).json has wrong fill-color (white) as below:
```
    {
      "id": "topographic area unclassified fill",
      "type": "fill",
      "source": "OSMasterMapTopography_gb_TopographicArea",
      "source-layer": "topographic_area",
      "filter": ["all", ["==", "style_code", 99]],
      "layout": {"visibility": "visible"},
      "paint": {"fill-color": "rgba(255, 255, 255, 1)"}
    }
```

The rgba values should match the OSMM-Topography-Layer-Colour-Values.xlsx colour values (248,246,240)

**Comment by egil1978** [comment]
Hi @cam-brown the style referenced in the OSMM-Topography-Layer-Colour-Values.xlsx document is for the Outdoor style and not Standard. The plan is to update the document with the colour values for all styles.
<img width="222" alt="image" src="https://user-images.githubusercontent.com/6939088/220131031-e20359c2-14b7-42cb-a56a-281f4cd0bc38.png">
