### ISSUE TITLE
All Schema version 9 SLD files have duplicated extension

### ISSUE THREAD

**Issue by mpdaly** [OrdnanceSurvey/OSMM-Topography-Layer-stylesheets#5]
eg

[boundaryline-backdrop.sld.sld](https://github.com/OrdnanceSurvey/OSMM-Topography-Layer-stylesheets/blob/master/Schema%20version%209/Stylesheets/Geoserver%20stylesheets%20(SLD)/boundaryline-backdrop.sld.sld)

**Comment by charleyglynn** [comment]
Thanks for the note @mpdaly all fixed now.
