### ISSUE TITLE
Inconsistent Assignment of Topographic Line Feature Style Codes

### ISSUE THREAD

**Issue by sab56** [OrdnanceSurvey/OSMM-Topography-Layer-stylesheets#8]
Style codes assigned to topographic line features using the Oracle SQL script are different to the codes assigned using the PostGIS SQL script. For example, topographic line features with a descriptive term of 'Polygon Closing Link' are assigned a code of 1 by the Oracle SQL script, whereas the PostGIS SQL script assigns code 6.

**Comment by charleyglynn** [comment]
Thanks for raising this issue. A new version of the SQL has now been uploaded. Cheers
