### ISSUE TITLE
New Topographic Line Styles Missing from Oracle Script

### ISSUE THREAD

**Issue by sab56** [OrdnanceSurvey/OSMM-Topography-Layer-stylesheets#9]
The Oracle script for updating the topographic line styles does not include the 3 new style types: 'Line Of Posts Line', 'Drain Line' and 'Normal Tidal Limit Line'.

**Comment by charleyglynn** [comment]
Thanks for raising this issue. A new version of the SQL has now been uploaded. Cheers

**Comment by sab56** [comment]
👍 Cheers Charley,
Steve Baker
